name: Destroy Server

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy_server:
    name: Destroy Server Target
    runs-on: ubuntu-latest
    environment: Main
    concurrency: deploy-group
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Targets
        run: terraform destroy -target=upcloud_server.teamspeak -target=cloudflare_dns_record.ts_dns -auto-approve
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          TF_VAR_upcloud_username: ${{ secrets.UPCLOUD_USERNAME }}
          TF_VAR_upcloud_password: ${{ secrets.UPCLOUD_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_query_admin_password: ${{ secrets.QUERY_ADMIN_PASSWORD }}
          TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
